name: Recipe Proxy
version: "1.0.0"
slug: recipe-proxy
description: Proxy to a local recipe application
url: https://github.com/Ephis/ha-recipe-proxy-app
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config
startup: application
boot: auto
hassio_api: true
ingress: true
ingress_port: 5000
panel_icon: mdi:food
panel_title: Recipes
options:
  frontend_server: "http://192.168.0.175:4200"
  backend_server: "http://192.168.0.175:5000"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  frontend_server: url
  backend_server: url
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
